- name: Install nginx
  ansible.builtin.apt:
    name: nginx

- name: Install nginx conf for loadbalancer
  when: ansible_hostname == "haproxy"
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Execute template for webserver
  when: ansible_hostname != "haproxy"
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html